### ISSUE TITLE
微信分享、微信登录时，在微信页面取消、关闭或退出时，app报错退出了

### ISSUE THREAD

**Issue by hongshu123** [yorkie/react-native-wechat#228]
安卓版本的
微信分享、微信登录时，不想分享了，在微信页面取消、关闭或退出时，app就直接报错退出了，停止运行。

如果是正确的分享了、或登录了的话，就是好的，没有问题

rn 44
wechat 最新版本

我把 index.js 里的  下面一句注释了就没有报错了
```
export class WechatError extends Error {
  constructor(resp) {    
    // https://github.com/babel/babel/issues/3083
    // Object.setPrototypeOf(this, WechatError.prototype);   // 这句注释掉，就好了
  }
}
```

手机的报告如下：
```
com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'Object.setPrototypeOf(t,r.prototype)'), stack:
r@468:2526
<unknown>@468:881
s@469:2097
emit@469:907
<unknown>@468:1768
value@56:1364
value@43:3000
<unknown>@43:941
value@43:2401
value@43:913

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:135)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by yorkie** [comment]
可以试试下面的Patch吗：

```diff
diff --git a/index.js b/index.js
index bc136d3..4fdf6fe 100644
--- a/index.js
+++ b/index.js
@@ -267,7 +267,11 @@ export class WechatError extends Error {

     // avoid babel's limition about extending Error class
     // https://github.com/babel/babel/issues/3083
-    Object.setPrototypeOf(this, WechatError.prototype);
+    if (typeof Object.setPrototypeOf === 'function') {
+      Object.setPrototypeOf(this, WechatError.prototype);
+    } else {
+      this.__proto__ = WechatError.prototype;
+    }
   }
 }
```

**Comment by hongshu123** [comment]
恩，可以了

**Comment by yorkie** [comment]
好的 可能是有一些版本里 Object.setPrototypeOf 不存在，我先把 Patch 放出来，后续我再问问 React-Native 社区那边啥情况好了 :)

**Comment by yorkie** [comment]
这个问题已经在 v1.9.5 中修复 @hongshu123
