### ISSUE TITLE
分享到微信后取消返回应用闪退

### ISSUE THREAD

**Issue by ZoroLu** [yorkie/react-native-wechat#337]
分享到微信又取消会闪退，看到两个一样的 issue, 但是问题好像不一样。我把 log 发出来,.

:37.717 14991-15077/com.yunao.myapp E/ReactNativeJS: Can't find variable: Reflect
02-01 20:33:37.762 14991-15078/com.yunao. myapp E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                  Process: com.yunao.freego, PID: 14991
                                                                  com.facebook.react.common.JavascriptException: Can't find variable:                                , stack:
                                                                  ExtendableBuiltin@100947:27
                                                                  WechatError@101133:116
                                                                  <unknown>@101078:31
                                                                  g@101262:21
                                                                  emit@101198:21
                                                                  <unknown>@100976:15
                                                                  emit@20953:40
                                                                  __callFunction@9085:47
                                                                  <unknown>@8901:29
                                                                  __guard@9056:11
                                                                  callFunctionReturnFlushedQueue@8900:20
                                                                  
                                                                      at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
                                                                      at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
                                                                      at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                      at java.lang.Thread.run(Thread.java:761)

**Comment by yoyo0427** [comment]
@ZoroLu 请问一下你是怎么解决的这个问题？

**Comment by ZoroLu** [comment]
@yoyo0427 我遇到的是语法问题。把 index.js 中的 WechatError 这个类，按照上面提到的参考链接的方式修改。但那已经是很久以前的事情了。
