### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.

### ISSUE THREAD

**Issue by Nocturne-FFG** [yorkie/react-native-wechat#415]
rn : 0.52.2
![image](https://user-images.githubusercontent.com/45280212/49986945-98558780-ffac-11e8-89ed-e5055bf530cd.png)

错误：
> Task :app:transformDexArchiveWithDexMergerForDebug FAILED
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/56, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/externalLibsDexMerger/debug/0, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/49.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/50.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/51.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/52.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/53.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/54.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/55.jar
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:397)
        at com.android.build.gradle.internal.transforms.DexMergerTransform.transform(DexMergerTransform.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
        at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/56, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/externalLibsDexMerger/debug/0, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/49.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/50.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/51.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/52.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/53.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/54.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/55.jar
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/56, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/externalLibsDexMerger/debug/0, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/49.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/50.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/51.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/52.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/53.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/54.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/55.jar
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:124)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:109)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:36)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        ... 4 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
        at com.android.tools.r8.D8.run(D8.java:88)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
        ... 7 more
Caused by: com.android.tools.r8.utils.AbortException
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:67)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:62)
        ... 10 more
        Suppressed: com.android.tools.r8.errors.DexOverflowException: Cannot fit requested classes in a single dex file (# methods: 65938 > 65536)
                at com.android.tools.r8.dex.VirtualFile.throwIfFull(VirtualFile.java:182)
                at com.android.tools.r8.dex.VirtualFile$MonoDexDistributor.run(VirtualFile.java:395)
                at com.android.tools.r8.dex.ApplicationWriter.distribute(ApplicationWriter.java:144)
                at com.android.tools.r8.dex.ApplicationWriter.write(ApplicationWriter.java:164)
                at com.android.tools.r8.D8.run(D8.java:167)
                at com.android.tools.r8.D8.lambda$run$1(D8.java:91)
                at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:58)
                ... 10 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/56, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/externalLibsDexMerger/debug/0, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/49.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/50.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/51.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/52.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/53.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/54.jar, /Users/moonlitnight/Documents/jyserverapp/android/app/build/intermediates/transforms/dexBuilder/debug/55.jar
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
134 actionable tasks: 127 executed, 7 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by Nocturne-FFG** [comment]
android 和java 一窍不同，完全看不懂

**Comment by Nocturne-FFG** [comment]
特么发完这个问题它就奇迹般的编译成功了，犹如见了鬼一般..........
