### ISSUE TITLE
微信调起闪退

### ISSUE THREAD

**Issue by outofmemory** [yorkie/react-native-wechat#549]
Please read and follow the issue templates:

1. Bug Report or Documentation Issue or Questions and Help?
YES
2. Which `react-native-wechat` version are you using?
1.9.12
3. What platform does your issue occur on? (Android/iOS/Both)
android
4. Please provide a clear and concise description of what the bug is as precisely as possible，you can: 

Logs from Sentry：
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.tencent.mm.sdk.openapi.IWXAPI.handleIntent(android.content.Intent, com.tencent.mm.sdk.openapi.IWXAPIEventHandler)' on a null object reference
    at com.theweflex.react.WeChatModule.handleIntent(WeChatModule.java:2)
    at com.xxxx.xxxx.wxapi.WXEntryActivity.onCreate(WXEntryActivity.java:2)
    at android.app.Activity.performCreate(Activity.java:6355)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2440)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2547)
    at android.app.ActivityThread.access$1100(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:157)
    at android.app.ActivityThread.main(ActivityThread.java:5603)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-native-wechat |  ^ 1.9.12
| react-native     | ^ 2.0.1
| node             | ^ 12.14.1.
| npm or yarn      | ^ 6.13.7

**Comment by cgz36** [comment]
Got the same problem. Any solution?

**Comment by outofmemory** [comment]
> Got the same problem. Any solution?

https://github.com/yorkie/react-native-wechat/pull/550/commits/b34cd45ff0d5d5826ec2c7224a05c024d20395e9

**Comment by cgz36** [comment]
> > Got the same problem. Any solution?
> 
> [b34cd45](https://github.com/yorkie/react-native-wechat/commit/b34cd45ff0d5d5826ec2c7224a05c024d20395e9)

Thank you. Add null check seems right.

`public static void handleIntent(Intent intent) {
        for (WeChatModule mod : modules) {
            if (mod.api != null) {
                mod.api.handleIntent(intent, mod);
            }
        }
    }`

**Comment by aoarashi1988** [comment]
Actually , this issue is probably occered when you use functional api without register the app
